micronaut:
  application:
    name: facecheck
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: "${FC_DB_URL:`jdbc:h2:file:./.db/h2/facecheck;AUTO_SERVER=TRUE;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE`}"
    driverClassName: "${FC_DB_DRIVER:`org.h2.Driver`}"
    username: "${FC_DB_USER:'sa'}"
    password: "${FC_DB_PASSWORD:}"
    dialect: "${FC_DB_DIALECT:h2}"
    schema-generate: "${FC_DB_SCHEMAGENERATE:`create_drop`}"
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-master.xml'
facecheck:
  debug:
    exception-message: false
aws:
  aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
  aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
