micronaut:
  application:
    name: facecheck
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/facecheck
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: none
    dialect: mysql
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-master.xml'
facecheck:
  debug:
    exception-message: true
