datasources:
  default:
    url: jdbc:h2:mem:test;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
    schema-generate: CREATE_DROP
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-test.xml'
