version: '3'
services:
  api:
    image: facecheck-api:latest
    container_name: facecheck-api
    networks:
      - api-network
    #      - spa-network
    ports:
      - 8080:8080
#  spa:
#    image: facecheck-spa:latest
#    container_name: facecheck-spa
#    ports:
#      - '80:80'
#    networks:
#      - spa-network
#    depends_on:
#      - api
networks:
  #  spa-network:
  #    driver: bridge
  api-network:
    driver: bridge
